# Generated by Django 3.1.3 on 2021-05-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('host', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField(max_length=10)),
            ],
        ),
    ]
