# Generated by Django 3.1.3 on 2021-05-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NesaraAssociation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='site_no',
            field=models.IntegerField(default=False),
        ),
    ]
