# Generated by Django 3.1.3 on 2021-05-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NesaraAssociation', '0002_member_site_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
