# Generated by Django 3.1.3 on 2021-05-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NesaraAssociation', '0003_auto_20210511_1105'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='NesaraAssociation_member',
        ),
    ]
