# Generated by Django 3.1.3 on 2021-05-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NesaraAssociation', '0004_auto_20210511_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_no',
            field=models.IntegerField(default=False),
        ),
    ]
